FROM golang:1.19

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY api/v2/server/go.mod ./
# COPY api/v2/server/go.sum ./
RUN go mod download && go mod verify

COPY api/v2 api/v2
RUN go build -v -o /usr/local/bin/app ./api/v2/main.go
EXPOSE 80

CMD ["app"]