FROM golang:1.19

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY api/v2/server/go.mod ./
# COPY api/v2/server/go.sum ./
RUN go mod download && go mod verify

COPY api/v2 api/v2
# RUN echo "test"
# RUN ls -l / > /tmp/test.txt
# RUN ls -l ./
# RUN ls -lah ./
RUN go build -v -o /usr/local/bin/app ./api/v2/server/main.go
EXPOSE 8080

CMD ["app"]