apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: booksys
        - name: DB_PASSWORD
          value: userpassword
        - name: DB_SERVER
          value: db:3306
        - name: DB_USER
          value: user
        image: booksys_ui
        imagePullPolicy: ""
        name: ui
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: ui-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: ui-claim0
        persistentVolumeClaim:
          claimName: ui-claim0
status: {}
