version: '3.3'

services:
    traefik:
        image: "traefik:latest"
        container_name: "traefik"
        command:
          #- "--log.level=DEBUG"
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=true"
          - "--entrypoints.web.address=:80"
        ports:
          - "80:80"
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
    db:
        image: booksys_dummy_db:latest
        environment:
            MYSQL_DATABASE: 'booksys'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'userpassword'
            MYSQL_ROOT_PASSWORD: 'rootpassword'
        ports:
            - '3306:3306'
        expose:
            - '3306'
    backend:
        image: booksys_ui:latest
        environment:
            DB_SERVER: 'db:3306'
            DB_NAME: 'booksys'
            DB_USER: 'user'
            DB_PASSWORD: 'userpassword'
        # ports:
        #     - '8081:80'
        # expose:
        #     - '80'
        labels:
            - "traefik.http.routers.backend.rule=PathPrefix(`/api/`) || PathPrefix(`/api`)"
            - "traefik.http.services.backend.loadbalancer.server.port=80"
            # - traefik.http.middlewares.backend.stripprefix.prefixes=/backend
            # - traefik.http.middlewares.backend.stripprefix.forceslash=false
            # - "traefik.http.middlewares.remove-backend.stripprefix.prefixes="
            # - "traefik.http.routers.backend.middlewares=remove-backend@docker"
        volumes:
            - ${PWD}/../../src/:/var/www/html
            - ${PWD}/config.php:/var/www/html/config/config.php
    frontend:
        image: "node:14"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
        volumes:
            - ../../src/app/booksys-vue:/home/node/app
        # ports:
        #     - "8082:8080"
        labels:
            - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
            - "traefik.http.services.frontend.loadbalancer.server.port=8080"
        #command: "npm start"
        command: "npm run serve"
    
