services:
    traefik:
        image: "traefik:latest"
        container_name: "fresh_ext_backend_traefik"
        command:
          - "--api.insecure=true"
          - "--api.dashboard=true"
          - "--accesslog=true"
        #   - "--log.level=DEBUG"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.traefik.address=:8081"
          - "--providers.file.directory=/etc/traefik/dynamic_conf" # Or use --providers.file.filename=/etc/traefik/dynamic_config.yml
          - "--providers.file.watch=true"
        ports:
          - "127.0.0.1:8080:80"
          - "127.0.0.1:8081:8081"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "./traefik:/etc/traefik/dynamic_conf:ro"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.traefik.rule=PathPrefix(`/`)"
          - "traefik.http.routers.traefik.entrypoints=traefik"
          - "traefik.http.services.traefik.loadbalancer.server.port=8081"
    db:
        build: "./database"
        container_name: "fresh_ext_backend_db"
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        ports:
            - '127.0.0.1:3306:3306'
        expose:
            - '3306'