#!/bin/bash

source .env
export BOOKSYS_MYNAUTIQUE_API_KEY=${BOOKSYS_MYNAUTIQUE_API_KEY}
export BOOKSYS_DATABASE_HOST=${LOCAL_DATABASE_HOST}
export BOOKSYS_DATABASE_PORT=${LOCAL_DATABASE_PORT}
export BOOKSYS_DATABASE_DBNAME=${MYSQL_DATABASE}
export BOOKSYS_DATABASE_USER=${MYSQL_USER}
export BOOKSYS_DATABASE_PASSWORD=${MYSQL_PASSWORD}

dir=`pwd`
cd ../../backend/api/v2
go run main.go --http_port 9090 --http_websetup
cd ${dir}