configfile: config.yaml
database:
    dbname: booksys
    host: 127.0.0.1
    password: userpassword
    port: "3306"
    protocol: tcp
    user: user
http:
    sessioninactivitytimeout: 604800
    sessiontimeout: 31536000
mynautique:
    apikey: AIzaSyAb8S3Owvo8k-gI8eK_DEztFOn0FcZFRxw
    enabled: true
    password: test
    user: test@example.com
port: 9090
upload:
    path: ./uploads
