config: ./mynewconfig.yaml
database:
    dbname: booksys
    host: 127.0.0.1
    password: userpassword
    port: "3306"
    protocol: tcp
    user: user
http:
    port: 9090
    sessioninactivitytimeout: "604800"
    sessiontimeout: "31536000"
    upload_path: ./uploads
    uploadpath: ./uploads
mynautique:
    api:
        key: ""
