name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image UI
      run: docker build . --file frontend/Dockerfile --tag booksys_frontend:$(date +%s)
    - name: Build the Docker image backend
      run: docker build . --file backend/Dockerfile --tag booksys_backend:$(date +%s)
